name: dailywords
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cloud_firestore: ^4.8.4
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^6.0.1
  google_sign_in: ^6.1.4
  lottie: ^2.5.0
  shared_preferences: ^2.2.0
  sign_in_with_apple: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/home.png
    - assets/statistics.png
    - assets/account.png
    - assets/home_inactive.png
    - assets/statistics_inactive.png
    - assets/account_inactive.png
    - assets/back.png
    - assets/done.png
    - assets/eye.png
    - assets/settings.png
    - assets/animations/DW_logo.json
    - assets/animations/eye_lottie.json
    - assets/globe.png
    - assets/down.png
    - assets/Apple.png
    - assets/Facebook.png
    - assets/Google.png

  fonts:
    - family: 'K_GothamPro'
      fonts:
        - asset: assets/fonts/K_GothamPro-Black.otf
          weight: 900
        - asset: assets/fonts/K_GothamPro-Medium.otf
          weight: 500
        - asset: assets/fonts/K_GothamPro-Regular.otf
          weight: 400   

